--- 
title: "Prelim"
subtitle: "Prelim a la NIH R01"
author: "Daniel Chen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, prelims.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Summary Statement {-}

- **_Aim 1: Identify learner personas in the biomedical sciences by creating and validating learner self-assessment surveys._**
  - 1.1: Learner self-assessment survey asking questions about prior programming, statistics, and data knowledge will be used to create learner personas.
  - 1.2: Personas will encompass a student's prior knowledge using survey data. General background, perception of needs, and special considerations will be added to make each learner persona a complete character.
- **_Aim 2: Create an effective data science for biomedical science curriculum based on best education and pedagogy practices._**
  - 2.1: Learning objectives focused around core data literacy principles in the data science pipeline will be used for each lesson module.
  - 2.2: Lesson content are created in blocks that can be remixed in classroom or workshop formats both in-person and virtually.
  - 2.3: Pre/post workshop survey looking at changes to learning objectives.
  - 2.4: Long-term survey will assess whether materials helped with retaining the fundamental knowledge.
  - 2.5: Post workshop will have a self-reported summative assessment question (i.e., final exam question).
  - 2.6: Workshop will have formative assessments to see if students are meeting learning objectives.
- **_Aim 3: Assess the short-term and long-term effectiveness of the curriculum based on learning objectives._**
  - 3.1: Create and evaluate a system that can capture formative assessment responses in a controlled study environment.
  - 3.2: Adding formative assessments in a programming data science context will help learners meet learning objectives tested in summative assessment questions.
